version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
